//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AK.F1.Timing {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AK.F1.Timing.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected non-empty string..
        /// </summary>
        internal static string ArgEmptyString {
            get {
                return ResourceManager.GetString("ArgEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected non-empty collection..
        /// </summary>
        internal static string ArgNonEmptyCollection {
            get {
                return ResourceManager.GetString("ArgNonEmptyCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to deserialize the next object as the object type code is invalid (&apos;{0}&apos;)..
        /// </summary>
        internal static string DecoratedObjectReader_InvalidObjectTypeCode {
            get {
                return ResourceManager.GetString("DecoratedObjectReader_InvalidObjectTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to deserialize the next object as the end of the serialization stream was unexpectedly reached..
        /// </summary>
        internal static string DecoratedObjectReader_UnexpectedEndOfStream {
            get {
                return ResourceManager.GetString("DecoratedObjectReader_UnexpectedEndOfStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot compare a &apos;{0}&apos; instance to an instance of &apos;{1}&apos;..
        /// </summary>
        internal static string LapGap_InvalidCompareToArgument {
            get {
                return ResourceManager.GetString("LapGap_InvalidCompareToArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable parse the next driver status message as the driver status value specified in the message (&apos;{0}&apos;) is invalid..
        /// </summary>
        internal static string LiveData_UnableToConvertToDriverStatus {
            get {
                return ResourceManager.GetString("LiveData_UnableToConvertToDriverStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse the next message as the grid column index &apos;{0}&apos; could not be converted to a GridColumn given the current session (&apos;{1}&apos;)..
        /// </summary>
        internal static string LiveData_UnableToConvertToGridColumn {
            get {
                return ResourceManager.GetString("LiveData_UnableToConvertToGridColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse the next message as the posted time type value specified in the message (&apos;{0}&apos;) is invalid..
        /// </summary>
        internal static string LiveData_UnableToConvertToPostedTimeType {
            get {
                return ResourceManager.GetString("LiveData_UnableToConvertToPostedTimeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable parse the next race status message as the race status value specified in the message (&apos;{0}&apos;) is invalid..
        /// </summary>
        internal static string LiveData_UnableToConvertToSessionStatus {
            get {
                return ResourceManager.GetString("LiveData_UnableToConvertToSessionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse the next this type message as the session type value specified in the message (&apos;{0}&apos;) is invalid..
        /// </summary>
        internal static string LiveData_UnableToConvertToSessionType {
            get {
                return ResourceManager.GetString("LiveData_UnableToConvertToSessionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse the next message as it contains an incorrectly formatted Double string (&apos;{0}&apos;)..
        /// </summary>
        internal static string LiveData_UnableToParseDouble {
            get {
                return ResourceManager.GetString("LiveData_UnableToParseDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse the next message as it contains an incorrectly formatted Int32 string (&apos;{0}&apos;)..
        /// </summary>
        internal static string LiveData_UnableToParseInt32 {
            get {
                return ResourceManager.GetString("LiveData_UnableToParseInt32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse the next message as the time value specified in the message (&apos;{0}&apos;) is invalid..
        /// </summary>
        internal static string LiveData_UnableToParseTime {
            get {
                return ResourceManager.GetString("LiveData_UnableToParseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied credentials have been rejected by the live timing server..
        /// </summary>
        internal static string LiveDecryptorFactory_CredentialsRejected {
            get {
                return ResourceManager.GetString("LiveDecryptorFactory_CredentialsRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse decryption seed from &apos;{0}&apos;..
        /// </summary>
        internal static string LiveDecryptorFactory_UnableToParseSeed {
            get {
                return ResourceManager.GetString("LiveDecryptorFactory_UnableToParseSeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of the next timing message (&apos;{0}&apos;) is not supported..
        /// </summary>
        internal static string LiveMessageReader_InvalidMessageType {
            get {
                return ResourceManager.GetString("LiveMessageReader_InvalidMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read the next message as the end of the message stream was unexpectedly reached..
        /// </summary>
        internal static string LiveMessageReader_UnexpectedEndOfStream {
            get {
                return ResourceManager.GetString("LiveMessageReader_UnexpectedEndOfStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read any messages from the stream as the first expected message was not an update keyframe message. The first message encountered was &apos;{0}&apos;..
        /// </summary>
        internal static string LiveMessageReader_UnexpectedFirstMessage {
            get {
                return ResourceManager.GetString("LiveMessageReader_UnexpectedFirstMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open a connection with the live timing servers as the &apos;{0}&apos; hostname failed to resolve..
        /// </summary>
        internal static string LiveMessageStreamEndpoint_FailedToResolveStreamHost {
            get {
                return ResourceManager.GetString("LiveMessageStreamEndpoint_FailedToResolveStreamHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format of the next timing message is invalid..
        /// </summary>
        internal static string MessageReader_InvalidMessage {
            get {
                return ResourceManager.GetString("MessageReader_InvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; type cannot be serialized as the &apos;{1}&apos; property is not decorated with the &apos;{2}&apos; attribute..
        /// </summary>
        internal static string PropertyDescriptor_PropertyIsNotDecorated {
            get {
                return ResourceManager.GetString("PropertyDescriptor_PropertyIsNotDecorated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This collection cannot be modified as it is sealed..
        /// </summary>
        internal static string PropertyDescriptorCollection_CollectionIsSealed {
            get {
                return ResourceManager.GetString("PropertyDescriptorCollection_CollectionIsSealed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; type already has a property with an identifier of &apos;{1}&apos;..
        /// </summary>
        internal static string PropertyDescriptorCollection_DuplicatePropertyDescriptor {
            get {
                return ResourceManager.GetString("PropertyDescriptorCollection_DuplicatePropertyDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot compare a {0} instance to an instance of {1}..
        /// </summary>
        internal static string TimeGap_InvalidCompareToArgument {
            get {
                return ResourceManager.GetString("TimeGap_InvalidCompareToArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to deserialize the next object as no type descriptor could be located for type &apos;{0}&apos;..
        /// </summary>
        internal static string TypeDescriptor_NoDescriptorWithTypeId {
            get {
                return ResourceManager.GetString("TypeDescriptor_NoDescriptorWithTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; type cannot be serialized as it is not decorated with the &apos;{1}&apos; attribute..
        /// </summary>
        internal static string TypeDescriptor_TypeIsNotDecorated {
            get {
                return ResourceManager.GetString("TypeDescriptor_TypeIsNotDecorated", resourceCulture);
            }
        }
    }
}
